---
title: "Data Synthesis Plan (Meta-Analysis)"
format: pdf
bibliography: 
  mylibrary.bib
csl: apa.csl
---

Statistical analysis of the data extracted will be performed in R, (v 4.3.3; R Core Team, https://www.r-project.org/) and RStudio (v 2023.06.1; Posit, https://posit.co/). All code utilised for data preparation and analyses are available in the corresponding GitHub repository <https://github.com/jamessteeleii/pcos_ree_meta>. We cite all software and packages used in the analysis pipeline using the `grateful` package [@rodriguez-sanchezGratefulFacilitateCitation2023] which can be seen here: [ADD LINKS](ADD LINK). 

The proposed analysis plan for data synthesis is part of the pre-registration on PROSPERO (update with registration number once complete). Given our research question our analysis aimed at parameter estimation [@cummingNewStatisticsWhy2014] within a Bayesian meta-analytic framework [@kruschkeBayesianNewStatistics2018]. For all analyses model parameter estimates and their precision, along with conclusions based upon them, will be interpreted continuously and probabilistically, considering data quality, plausibility of effect, and previous literature, all within the context of each model. The `renv` package [@usheyRenvProjectEnvironments2023] is used for package version reproducibility and a function based analysis pipeline using the `targets` package [@landauTargetsDynamicFunctionOriented2023] is employed (the analysis pipeline can be viewed by downloading the R Project and running the function `targets::tar_visnetwork()`). Effect sizes and their variances are all calculated using the `metafor` packages `escalc()` function [@viechtbauerMetaforMetaAnalysisPackage2023]. The main package `brms` [@burknerBrmsBayesianRegression2023] is used in fitting all the Bayesian meta-analysis models. Prior and posterior draws are taken using `tidybayes` [@kayTidybayesTidyData2023] and `marginaleffects` [@arel-bundockMarginaleffectsPredictionsComparisons2023] packages. All visualisations are created using `ggplot2` [@wickhamGgplot2CreateElegant2023], `tidybayes`, and the `patchwork` [@pedersenPatchworkComposerPlots2023] packages. Where data to be extracted from included studies is reported in plots only we will use the `juicr` package to extract this data [@lajeunesseJuicrAutomatedManual2021] and the reproducible reports for this will be found in the github repository.

As noted, we adopt a Bayesian approach to the present meta-analysis and examine both contrast-based models of studies with pairwise effects (i.e., relative contrasts between non-PCOS and PCOS arms), in addition to arm-based models. We adopt an arm-based multiple condition comparison (i.e., network) type model given that we know there will studies of women with PCOS both with, and without, a non-PCOS control arm [@hongBayesianMissingData2016]. In typical contrast-based meta-analyses data is limited to the effect sizes for paired contrasts between arms and thus studies that include both arms (i.e., relative effects between non-PCOS control vs PCOS arms); however, in arm-based analyses the data are the absolute effects within each arm and information is borrowed across studies to enable both within condition absolute, and between condition relative contrasts to be estimated. From this we focus on reporting the between condition relative contrast for non-PCOS control vs PCOS arms. The arm-based models, which are specified along with their priors in the `R/functions.R` file in `brms` syntax and explantory comments, will be our primary model and contrast-based models with weakly regularising default priors will also be presented in order to examine the sensitivity of findings to the inclusion of indirect evidence from single arm studies and prior information on overall inferences. The arm-based models are parameterised such that priors can be set informatively on the non-PCOS arms as the model intercept (and its random effect variance) and these are based on estimates from previous large scale studies (see comments in `R/functions.R`) of the resting energy expenditure of non-PCOS women, and the coefficient reflecting the relative contrast between non-PCOS controls and PCOS arms was set to be weakly informative based on the minimum and maximum ranges of resting energy expenditure as reflecting the possible range of differences that could in principle exist between two conditions. The priors for the variance effects (noted below) were similarly set based on these previous studies.  

We will examine both raw mean effects (i.e., for the arm-based model the absolute mean resting energy expenditure in kcals per day for each arm, and for the contrast-based model the absolute mean difference in resting energy expenditure in kcals per day between non-PCOS controls and PCOS arms) in addition to the variance effects (i.e., for the arm-based model the absolute standard deviation in resting energy expenditure in kcals per day for each arm, and for the contrast-based model the absolute difference in standard deviation in resting energy expenditure in kcals per day between non-PCOS controls and PCOS arms). For the variance effects the arm-based models will model the natural log transformation of the standard deviation as the effect outcome and include the natural log transformation of the mean (modelled with measurement error based on the natural log transformation of the standard error of the mean for each arm) to adjust for mean-variance relationships, and for the contrast based model will utilise the log coefficient of variation effect size statistic which also adjusts for mean-variance relationships. 

For all models we will examine trace plots along with $\hat{R}$ values to examine whether chains have converged, and posterior predictive checks for each model to understand the model implied distributions. From each model we will obtain draws from the posterior distributions for the conditional absolute estimates for each condition (i.e., non-PCOS controls and PCOS arms) by study, the global grand mean absolute estimates for each condition, and the between condition relative contrast for non-PCOS controls vs PCOS arms in order to present probability density functions visually, and also to calculate mean and 95% quantile intervals (i.e., 'credible' or 'compatibility' intervals) for each estimate. These will give us the most probable value of the parameter in addition to the range from 2.5% to 97.5% percentiles.

# References